### PR TITLE
global: addition of keyword arguments to get_schema.

### PR DESCRIPTION
**Pull request by krzysztof**
- Adds keyword arguments to get_schema method.

Signed-off-by: Krzysztof Nowak k.nowak@cern.ch

### CODE REVIEW

**Comment by krzysztof** [comment]
@nharraud Wanna take a quick look?

**Comment by nharraud** [comment]
@krzysztof Thanks, it looks good. Could you just add the parameter to the method's docstring, explaining that these arguments are given to `json.load`?

**Comment by lnielsen** [comment]
What do you need to customise in the JSON loader? Perhaps it could be solved by using `from flask import json`  instead of `import json` so that we use the Flask JSON serializer which has some few fixes.

I don't have any objections to the PR

**Comment by krzysztof** [comment]
@lnielsen I need to pass argument `object_pairs_hook=OrderedDict` to `json.load` so that the keys order is preserved in the loaded JSON.

**Comment by krzysztof** [comment]
@lnielsen From quick tests it seems that `flask.json` is also not preserving order of the keys.

**Comment by krzysztof** [comment]
In the end I am not using this feature and simply dumping the dict with keys sorted...

**Pull request closed without merging**
