### PR TITLE
global: current_jsonschema proxy addition

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Review by nharraud — APPROVED** [review]
@hachreak Thanks for the commit 👍

**Comment by nharraud** [comment]
@lnielsen can you merge this commit, I don't seem to have write permissions on this repo.

**Comment by lnielsen** [comment]
Now you have :-)

**Comment by nharraud** [comment]
@hachreak could you please rebase?

**Comment by hachreak** [comment]
:+1: done :smile:

**Pull request merged**
