### PR TITLE
Fixing issue #85 - resolve_schema: allOf inside allOf is ignored

### LINKED ISSUE #85: resolve_schema: allOf inside allOf is ignored
At https://github.com/inveniosoftware/invenio-jsonschemas/blob/master/invenio_jsonschemas/utils.py#L41-L47 allOf is popped from schema after parts of allOf are merged. If these parts contain another top-level allOf, it is ignored and its content is removed.

A fix might be:

    if 'allOf' in schema:
        all_of = schema.pop('allOf')
        for sub_schema in all_of:
            sub_schema.pop('title', None)
            sub_schema.pop('$id', None)
            schema = _merge_dicts(schema, sub_schema)
        schema = traverse(schema)

If you want, I can prepare a pull request.

### PR DESCRIPTION
**Pull request by mesemus**
reordered pop for allOf to fix #85

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks a lot for contributing the fix. Do you have an example schema that fails on the current method, and is being fixed by this PR. Then I can try to add a tests to the PR, to make sure it works in the future as well.

**Comment by slint** [comment]
@Glignos added such a schema to a test and checked that the fix makes it pass. I think he's pushing the test soon

**Comment by Glignos** [comment]
Superseded by #94

**Comment by lnielsen** [comment]
Closed by #94

**Pull request closed without merging**
